language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
    - python: 3.6
    - python: 3.8-dev
      dist: xenial

install:
 - pip install -U pip
 - pip install -U black flake8 freezegun pytest pytest-cov requests_mock
 - pip install -e .

script:
 # Unit tests
 - pytest --cov pypistats

 # Static analysis
 - flake8 --statistics --count .
 - black --check --diff .

 # Test runs
 - pypistats --help
 - pypistats recent --help

after_success:
  - coverage report
  - pip install -U codecov && codecov

deploy:
  - provider: pypi
    server: https://test.pypi.org/legacy/
    on:
      tags: false
      repo: hugovk/pypistats
      branch: master
      python: 3.7
    user: hugovk
    password:
      secure: MR3i+/8ZscMkgDlAQkbZxnAuvmHebfGqZzih2nlL8DoINx063ewqISsxhFtAIuyuFPUFu1F2urz2oXVlhc5jxulwSMkjTRGEb4NCCGcZvvPrIQw7nazRXo57o4AkVYuFMne3Bu8YU1R5gugeJenG0WdDXtjZkHrSjX2YzWUyYgdRbC5/KG3XHaVLSNtRebICxMYNj4Py22qh/B9rvXoKMAcgJHYf/FeAZhnYf25xzZBK8oiRv2ELRPogbTCDaCuFz6XDFHcx5WfV5jNfjeYaKzKPiHZhcKbyVDGFODRKa98mVhDTaVOcq4oCysGP/uz96cu67FOxk7wHRzZf8HV6WTgh2n3Zvokkm+uXb4rQlteAdYPfgeqtcgKXIj9WmGL48dw2f72oGahLDjQEXfzJzX3LaRgAd99TMFsGpbKlU9mfmfz/SOXyUA7ZAB6iEw0TsYosoffblH/q+1BjE0nIhY9xoP3KOz44TtUUSdtW4ztRQXrGzZkCiNqbSmZwqL+IhJRSHHsxggDaUI0N2c2f10IJHVUDgMjz4IjutdXgcwRTe8UCzQ/maeRI0epZAtC9UQ6ix5zKlR20IIzhP0rOinhk3vKCpINzofk46fkgKC7tM7Lchip0URQ6vnQxhG99wn7MZbOgTNp7fZduaFEfe72oIjCfDv1nTrRkr0dI5Cc=
    distributions: sdist --format=gztar bdist_wheel
    skip_existing: true
  - provider: pypi
    on:
      tags: true
      repo: hugovk/pypistats
      branch: master
      python: 3.7
    user: hugovk
    password:
      secure: MR3i+/8ZscMkgDlAQkbZxnAuvmHebfGqZzih2nlL8DoINx063ewqISsxhFtAIuyuFPUFu1F2urz2oXVlhc5jxulwSMkjTRGEb4NCCGcZvvPrIQw7nazRXo57o4AkVYuFMne3Bu8YU1R5gugeJenG0WdDXtjZkHrSjX2YzWUyYgdRbC5/KG3XHaVLSNtRebICxMYNj4Py22qh/B9rvXoKMAcgJHYf/FeAZhnYf25xzZBK8oiRv2ELRPogbTCDaCuFz6XDFHcx5WfV5jNfjeYaKzKPiHZhcKbyVDGFODRKa98mVhDTaVOcq4oCysGP/uz96cu67FOxk7wHRzZf8HV6WTgh2n3Zvokkm+uXb4rQlteAdYPfgeqtcgKXIj9WmGL48dw2f72oGahLDjQEXfzJzX3LaRgAd99TMFsGpbKlU9mfmfz/SOXyUA7ZAB6iEw0TsYosoffblH/q+1BjE0nIhY9xoP3KOz44TtUUSdtW4ztRQXrGzZkCiNqbSmZwqL+IhJRSHHsxggDaUI0N2c2f10IJHVUDgMjz4IjutdXgcwRTe8UCzQ/maeRI0epZAtC9UQ6ix5zKlR20IIzhP0rOinhk3vKCpINzofk46fkgKC7tM7Lchip0URQ6vnQxhG99wn7MZbOgTNp7fZduaFEfe72oIjCfDv1nTrRkr0dI5Cc=
    distributions: sdist --format=gztar bdist_wheel
    skip_existing: true
