language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.6

install:
 - pip install -U pip
 - pip install -U black flake8 freezegun pytest pytest-cov requests_mock
 - pip install -e .

script:
 # Unit tests
 - pytest --cov pypistats

 # Static analysis
 - flake8 --statistics --count .
 - black --check --diff .

 # Test runs
 - pypistats --help
 - pypistats recent --help

after_success:
  - coverage report
  - pip install -U codecov && codecov
