language: python
cache: pip
sudo: false

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.6

install:
 - pip install -U pip
 - pip install -U flake8 freezegun pytest pytest-cov requests_mock
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install -U black; fi
 - pip install -e .

script:
 # Unit tests
 - pytest --cov pypistats

 # Static analysis
 - flake8 --statistics --count
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --check --diff .; fi

 # Test runs
 - pypistats --help
 - pypistats recent --help

after_success:
  - coverage report
  - pip install -U codecov && codecov
