name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@master
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pre-commit
          key:
            lint-v2-${{ hashFiles('**/setup.py') }}-${{
            hashFiles('**/.pre-commit-config.yaml') }}
          restore-keys: |
            lint-v2-

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U tox

      - name: Lint
        run: tox -e lint
